bot:
  username: wimmly_bot
  token: ${BOT_TOKEN}
spring:
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: "Async-"
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bot}
    username: ${DB_USER:postgres}
    password: ${DB_PSWRD:postgres}
logging:
  level:
    ru.telegram.bot.adapter: DEBUG
    org.springframework.web: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

clients:
  budget:
    url: ${BUDGET_URL:http://localhost:8181}