bot:
  username: wimmly_bot
  token: ${BOT_TOKEN}
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kotlin_template}
    username: ${DB_USER:postgres}
    password: ${DB_PSWRD:postgres}
logging:
  level:
    root: info