spring:
  datasource:
    url: {DB_URL:jdbc:postgresql://localhost:5432/wimmly}
    username: ${DB_USER:postgres}
    password: ${DB_PSWRD:postgres}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: test, default
    default-schema: public
    drop-first: false
logging:
  level:
    root: info